version: 1.0.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

before_build:
  - dotnet tool install -g coveralls.net --version 1.0.0
  - nuget restore ./src

nuget:
  account_feed: true
  project_feed: true

build:
  publish_nuget: true
  verbosity: minimal

test_script:
  - dotnet test --filter Category=Unit /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*" ./src/DeltaObjectGeneratorTests/DeltaObjectGeneratorTests.csproj
  - csmacnz.coveralls --opencover --useRelativePaths -i C:\projects\deltaobjectgenerator\src\DeltaObjectGeneratorTests\coverage.opencover.xml

deploy:
  provider: NuGet
  server:
  api_key:
    secure: VdvNwzCbxAZai/ljtAa/fg5bkCfHWxEiDkNFiuEEI1+O8nVSwM9TerXp8AsWftL5
  skip_symbols: true
  artifact: /.*\.nupkg/
